"""
Item definitions, loot tables, and crafting recipes.
"""

from constants import *


ITEMS = {
    "wood": {
        "name": "Wood",
        "type": ITEM_RESOURCE,
        "stack": 64,
        "value": 2,
        "color": (120, 85, 45),
        "description": "Sturdy timber. Used in many recipes and structures.",
    },
    "stone": {
        "name": "Stone",
        "type": ITEM_RESOURCE,
        "stack": 64,
        "value": 1,
        "color": (140, 140, 150),
        "description": "Hard rock for tools, walls, and furnaces.",
    },
    "fiber": {
        "name": "Plant Fiber",
        "type": ITEM_RESOURCE,
        "stack": 64,
        "value": 1,
        "color": (150, 180, 90),
        "description": "Useful for primitive bindings and rope.",
    },
    "berry": {
        "name": "Berries",
        "type": ITEM_FOOD,
        "stack": 20,
        "value": 3,
        "food_restore": 15,
        "color": (180, 40, 80),
        "description": "Plump wild berries. Restores 15 hunger.",
    },
    "wheat": {
        "name": "Wheat",
        "type": ITEM_RESOURCE,
        "stack": 40,
        "value": 3,
        "color": (214, 186, 86),
        "description": "Golden grain harvested from village fields.",
    },
    "bread": {
        "name": "Bread",
        "type": ITEM_FOOD,
        "stack": 16,
        "value": 9,
        "food_restore": 35,
        "color": (196, 148, 78),
        "description": "Fresh baked bread. Restores 35 hunger.",
    },
    "mushroom": {
        "name": "Mushroom",
        "type": ITEM_FOOD,
        "stack": 20,
        "value": 4,
        "food_restore": 20,
        "color": (180, 100, 50),
        "description": "Earthy mushroom. Restores 20 hunger.",
    },
    "flower": {
        "name": "Wildflower",
        "type": ITEM_MISC,
        "stack": 20,
        "value": 2,
        "color": (220, 180, 60),
        "description": "Bright petals from the wild.",
    },
    "reed": {
        "name": "Reeds",
        "type": ITEM_RESOURCE,
        "stack": 30,
        "value": 1,
        "color": (110, 150, 70),
        "description": "Tall reeds from the water's edge.",
    },
    "flint": {
        "name": "Flint",
        "type": ITEM_RESOURCE,
        "stack": 20,
        "value": 3,
        "color": (100, 95, 110),
        "description": "Sharp flint for early tools.",
    },
    "vine": {
        "name": "Vine",
        "type": ITEM_RESOURCE,
        "stack": 30,
        "value": 2,
        "color": (60, 140, 60),
        "description": "Tough plant vines. Good for bindings.",
    },
    "feather": {
        "name": "Feather",
        "type": ITEM_RESOURCE,
        "stack": 20,
        "value": 3,
        "color": (230, 220, 200),
        "description": "A light feather from a creature.",
    },
    "hide": {
        "name": "Animal Hide",
        "type": ITEM_RESOURCE,
        "stack": 10,
        "value": 8,
        "color": (160, 120, 75),
        "description": "Can be tanned into leather.",
    },
    "meat_raw": {
        "name": "Raw Meat",
        "type": ITEM_FOOD,
        "stack": 10,
        "value": 5,
        "food_restore": 8,
        "color": (200, 90, 90),
        "description": "Can be cooked at a campfire.",
    },
    "meat_cooked": {
        "name": "Cooked Meat",
        "type": ITEM_FOOD,
        "stack": 10,
        "value": 10,
        "food_restore": 35,
        "color": (160, 70, 40),
        "description": "Juicy cooked meat. Restores 35 hunger.",
    },
    "rope": {
        "name": "Rope",
        "type": ITEM_MATERIAL,
        "stack": 20,
        "value": 5,
        "color": (180, 150, 80),
        "description": "Braided rope for tools and doors.",
    },
    "leather": {
        "name": "Leather",
        "type": ITEM_MATERIAL,
        "stack": 10,
        "value": 12,
        "color": (140, 100, 55),
        "description": "Tanned leather.",
    },
    "coal": {
        "name": "Coal",
        "type": ITEM_RESOURCE,
        "stack": 32,
        "value": 4,
        "color": (60, 60, 60),
        "description": "Burns hot in a furnace.",
    },
    "iron_ore": {
        "name": "Iron Ore",
        "type": ITEM_RESOURCE,
        "stack": 32,
        "value": 6,
        "color": (122, 118, 110),
        "description": "Needs smelting in a furnace.",
    },
    "iron_ingot": {
        "name": "Iron Ingot",
        "type": ITEM_MATERIAL,
        "stack": 32,
        "value": 10,
        "color": (190, 190, 200),
        "description": "Refined metal for advanced gear.",
    },
    "axe_wood": {
        "name": "Wood Axe",
        "type": ITEM_TOOL,
        "stack": 1,
        "value": 8,
        "durability": 40,
        "damage": 6,
        "harvest_power": 1,
        "speed": 0.9,
        "harvest_tags": ["tree", "wood"],
        "tool_family": "axe",
        "tier": "wood",
        "color": (150, 110, 65),
        "description": "A rough wooden axe.",
    },
    "axe_stone": {
        "name": "Stone Axe",
        "type": ITEM_TOOL,
        "stack": 1,
        "value": 15,
        "durability": 80,
        "damage": 11,
        "harvest_power": 2,
        "speed": 1.0,
        "harvest_tags": ["tree", "wood"],
        "tool_family": "axe",
        "tier": "stone",
        "color": (140, 140, 150),
        "description": "Reliable for chopping trees.",
    },
    "axe_iron": {
        "name": "Iron Axe",
        "type": ITEM_TOOL,
        "stack": 1,
        "value": 30,
        "durability": 160,
        "damage": 17,
        "harvest_power": 3,
        "speed": 1.2,
        "harvest_tags": ["tree", "wood"],
        "tool_family": "axe",
        "tier": "iron",
        "color": (180, 190, 200),
        "description": "Chops efficiently and lasts a long time.",
    },
    "pickaxe_wood": {
        "name": "Wood Pickaxe",
        "type": ITEM_TOOL,
        "stack": 1,
        "value": 8,
        "durability": 35,
        "damage": 5,
        "harvest_power": 1,
        "speed": 0.85,
        "harvest_tags": ["stone", "ore"],
        "tool_family": "pickaxe",
        "tier": "wood",
        "color": (150, 110, 65),
        "description": "Barely good enough for soft stone.",
    },
    "pickaxe_stone": {
        "name": "Stone Pickaxe",
        "type": ITEM_TOOL,
        "stack": 1,
        "value": 15,
        "durability": 80,
        "damage": 10,
        "harvest_power": 2,
        "speed": 1.0,
        "harvest_tags": ["stone", "ore"],
        "tool_family": "pickaxe",
        "tier": "stone",
        "color": (140, 140, 150),
        "description": "Mines stone and basic ore.",
    },
    "pickaxe_iron": {
        "name": "Iron Pickaxe",
        "type": ITEM_TOOL,
        "stack": 1,
        "value": 32,
        "durability": 165,
        "damage": 15,
        "harvest_power": 3,
        "speed": 1.25,
        "harvest_tags": ["stone", "ore"],
        "tool_family": "pickaxe",
        "tier": "iron",
        "color": (180, 190, 200),
        "description": "Mines ore quickly and cleanly.",
    },
    "hoe_wood": {
        "name": "Wood Hoe",
        "type": ITEM_TOOL,
        "stack": 1,
        "value": 7,
        "durability": 45,
        "damage": 4,
        "speed": 0.95,
        "tool_family": "hoe",
        "tier": "wood",
        "color": (154, 116, 68),
        "description": "Tills dirt into farmland.",
    },
    "hoe_stone": {
        "name": "Stone Hoe",
        "type": ITEM_TOOL,
        "stack": 1,
        "value": 14,
        "durability": 90,
        "damage": 6,
        "speed": 1.05,
        "tool_family": "hoe",
        "tier": "stone",
        "color": (142, 142, 150),
        "description": "Reliable for preparing tidy farm rows.",
    },
    "hoe_iron": {
        "name": "Iron Hoe",
        "type": ITEM_TOOL,
        "stack": 1,
        "value": 30,
        "durability": 180,
        "damage": 8,
        "speed": 1.15,
        "tool_family": "hoe",
        "tier": "iron",
        "color": (188, 196, 206),
        "description": "Quickly turns open ground into fertile rows.",
    },
    "sword_wood": {
        "name": "Wood Sword",
        "type": ITEM_WEAPON,
        "stack": 1,
        "value": 8,
        "durability": 50,
        "damage": 8,
        "attack_range": 62,
        "speed": 0.95,
        "tool_family": "sword",
        "tier": "wood",
        "color": (145, 105, 65),
        "description": "Simple but better than fists.",
    },
    "sword_stone": {
        "name": "Stone Sword",
        "type": ITEM_WEAPON,
        "stack": 1,
        "value": 17,
        "durability": 85,
        "damage": 14,
        "attack_range": 66,
        "speed": 1.0,
        "tool_family": "sword",
        "tier": "stone",
        "color": (135, 135, 145),
        "description": "Heavy, sharp, and dependable.",
    },
    "sword_iron": {
        "name": "Iron Sword",
        "type": ITEM_WEAPON,
        "stack": 1,
        "value": 36,
        "durability": 180,
        "damage": 21,
        "attack_range": 72,
        "speed": 1.15,
        "tool_family": "sword",
        "tier": "iron",
        "color": (195, 200, 210),
        "description": "A durable and deadly blade.",
    },
    "berry_seed": {
        "name": "Berry Seed",
        "type": ITEM_SEED,
        "stack": 20,
        "value": 3,
        "plant_type": "berry_bush",
        "color": (160, 60, 100),
        "description": "Plant on grass to grow a bush.",
    },
    "wheat_seed": {
        "name": "Wheat Seed",
        "type": ITEM_SEED,
        "stack": 24,
        "value": 3,
        "plant_type": "wheat_crop",
        "color": (220, 196, 104),
        "description": "Plant on farmland to grow wheat.",
    },
    "campfire": {
        "name": "Campfire",
        "type": ITEM_MATERIAL,
        "stack": 5,
        "value": 8,
        "color": (220, 120, 40),
        "placeable": "campfire",
        "description": "Place to cook food.",
    },
    "furnace": {
        "name": "Furnace",
        "type": ITEM_MATERIAL,
        "stack": 3,
        "value": 18,
        "color": (100, 100, 110),
        "placeable": "furnace",
        "description": "Needed for smelting ores into ingots.",
    },
    "wall_wood": {
        "name": "Wood Wall",
        "type": ITEM_MATERIAL,
        "stack": 32,
        "value": 4,
        "color": (120, 85, 45),
        "placeable": "wall_wood",
        "description": "A placeable wooden wall.",
    },
    "wall_stone": {
        "name": "Stone Wall",
        "type": ITEM_MATERIAL,
        "stack": 32,
        "value": 6,
        "color": (135, 135, 145),
        "placeable": "wall_stone",
        "description": "A solid placeable stone wall.",
    },
    "door_wood": {
        "name": "Wood Door",
        "type": ITEM_MATERIAL,
        "stack": 16,
        "value": 7,
        "color": (145, 100, 55),
        "placeable": "door_wood",
        "description": "Place and toggle it open or closed.",
    },
    "bed": {
        "name": "Bed",
        "type": ITEM_MATERIAL,
        "stack": 8,
        "value": 10,
        "color": (176, 62, 62),
        "placeable": "bed",
        "description": "A simple bed for a safe night's sleep.",
    },
    "chest_wood": {
        "name": "Wood Chest",
        "type": ITEM_MATERIAL,
        "stack": 8,
        "value": 12,
        "color": (134, 96, 54),
        "placeable": "chest_wood",
        "description": "A storage chest for supplies and crops.",
    },
}


LOOT_TABLES = {
    "tree": [
        ("wood", 4, 7, 1.0),
        ("vine", 1, 3, 0.45),
        ("feather", 1, 2, 0.12),
    ],
    "berry_bush": [
        ("berry", 2, 5, 1.0),
        ("fiber", 1, 2, 0.6),
        ("berry_seed", 1, 2, 0.35),
    ],
    "wheat_crop": [
        ("wheat", 2, 4, 1.0),
        ("wheat_seed", 1, 2, 0.7),
        ("fiber", 1, 2, 0.25),
    ],
    "mushroom_cluster": [
        ("mushroom", 2, 4, 1.0),
        ("fiber", 1, 2, 0.4),
    ],
    "flower_patch": [
        ("flower", 2, 5, 1.0),
        ("fiber", 1, 3, 0.7),
    ],
    "reed_patch": [
        ("reed", 3, 6, 1.0),
        ("fiber", 1, 3, 0.55),
    ],
    "stone_outcrop": [
        ("stone", 3, 6, 1.0),
        ("flint", 1, 3, 0.45),
    ],
    "coal_vein": [
        ("stone", 2, 4, 1.0),
        ("coal", 2, 5, 0.95),
    ],
    "iron_vein": [
        ("stone", 2, 4, 1.0),
        ("iron_ore", 2, 4, 0.9),
    ],
    "passive_creature": [
        ("meat_raw", 1, 2, 0.8),
        ("hide", 1, 1, 0.55),
        ("feather", 1, 3, 0.25),
    ],
    "neutral_creature": [
        ("meat_raw", 1, 3, 0.9),
        ("hide", 1, 2, 0.7),
        ("coal", 1, 2, 0.15),
    ],
    "hostile_creature": [
        ("meat_raw", 2, 4, 1.0),
        ("hide", 1, 2, 0.8),
        ("flint", 1, 2, 0.25),
        ("iron_ore", 1, 2, 0.12),
    ],
}


RECIPES = {
    "rope": {
        "result_qty": 1,
        "ingredients": {"fiber": 4},
        "station": None,
        "name": "Rope",
    },
    "campfire": {
        "result_qty": 1,
        "ingredients": {"wood": 5, "stone": 3},
        "station": None,
        "name": "Campfire",
    },
    "furnace": {
        "result_qty": 1,
        "ingredients": {"stone": 12, "coal": 2},
        "station": None,
        "name": "Furnace",
    },
    "wall_wood": {
        "result_qty": 2,
        "ingredients": {"wood": 4},
        "station": None,
        "name": "Wood Wall",
    },
    "wall_stone": {
        "result_qty": 2,
        "ingredients": {"stone": 6},
        "station": None,
        "name": "Stone Wall",
    },
    "door_wood": {
        "result_qty": 1,
        "ingredients": {"wood": 4, "rope": 1},
        "station": None,
        "name": "Wood Door",
    },
    "bed": {
        "result_qty": 1,
        "ingredients": {"wood": 4, "fiber": 3},
        "station": None,
        "name": "Bed",
    },
    "chest_wood": {
        "result_qty": 1,
        "ingredients": {"wood": 6, "rope": 1},
        "station": None,
        "name": "Wood Chest",
    },
    "axe_wood": {
        "result_qty": 1,
        "ingredients": {"wood": 3, "fiber": 2},
        "station": None,
        "name": "Wood Axe",
    },
    "pickaxe_wood": {
        "result_qty": 1,
        "ingredients": {"wood": 4, "fiber": 2},
        "station": None,
        "name": "Wood Pickaxe",
    },
    "sword_wood": {
        "result_qty": 1,
        "ingredients": {"wood": 4, "fiber": 1},
        "station": None,
        "name": "Wood Sword",
    },
    "axe_stone": {
        "result_qty": 1,
        "ingredients": {"wood": 2, "stone": 3, "vine": 1},
        "station": None,
        "name": "Stone Axe",
    },
    "pickaxe_stone": {
        "result_qty": 1,
        "ingredients": {"wood": 2, "stone": 4, "vine": 1},
        "station": None,
        "name": "Stone Pickaxe",
    },
    "hoe_wood": {
        "result_qty": 1,
        "ingredients": {"wood": 3, "fiber": 2},
        "station": None,
        "name": "Wood Hoe",
    },
    "sword_stone": {
        "result_qty": 1,
        "ingredients": {"wood": 2, "stone": 3, "rope": 1},
        "station": None,
        "name": "Stone Sword",
    },
    "hoe_stone": {
        "result_qty": 1,
        "ingredients": {"wood": 2, "stone": 3, "vine": 1},
        "station": None,
        "name": "Stone Hoe",
    },
    "iron_ingot": {
        "result_qty": 1,
        "ingredients": {"iron_ore": 1, "coal": 1},
        "station": "furnace",
        "name": "Iron Ingot",
    },
    "axe_iron": {
        "result_qty": 1,
        "ingredients": {"wood": 1, "iron_ingot": 3},
        "station": None,
        "name": "Iron Axe",
    },
    "pickaxe_iron": {
        "result_qty": 1,
        "ingredients": {"wood": 1, "iron_ingot": 3},
        "station": None,
        "name": "Iron Pickaxe",
    },
    "hoe_iron": {
        "result_qty": 1,
        "ingredients": {"wood": 1, "iron_ingot": 3},
        "station": None,
        "name": "Iron Hoe",
    },
    "sword_iron": {
        "result_qty": 1,
        "ingredients": {"wood": 1, "iron_ingot": 3},
        "station": None,
        "name": "Iron Sword",
    },
    "leather": {
        "result_qty": 1,
        "ingredients": {"hide": 2},
        "station": None,
        "name": "Leather",
    },
    "meat_cooked": {
        "result_qty": 1,
        "ingredients": {"meat_raw": 1, "wood": 1},
        "station": "campfire",
        "name": "Cooked Meat",
    },
    "berry_seed": {
        "result_qty": 2,
        "ingredients": {"berry": 3},
        "station": None,
        "name": "Berry Seeds",
    },
    "bread": {
        "result_qty": 1,
        "ingredients": {"wheat": 3},
        "station": None,
        "name": "Bread",
    },
}
